# https://github.com/marketplace/actions/labeler#usage
Documentation:
- changed-files:
  - any-glob-to-any-files: ['README.md', '**/README.md']

Server:
- changed-files:
  - any-glob-to-any-files: ['server/**', '.github/workflows/server.*', '.github/actions/cache-server/**']

scanner:
- changed-files:
  - any-glob-to-any-files: ['scanner/**', '.github/workflows/scanner.*', '.github/actions/cache-scanner/**']

Matcher:
- changed-files:
  - any-glob-to-any-files: ['matcher/**', '.github/workflows/matcher.*', '.github/actions/cache-matcher/**']

Front (Web):
- changed-files:
  - any-glob-to-any-files: ['front/apps/web/**']

Front (Mobile):
- changed-files:
  - any-glob-to-any-files: ['front/apps/mobile/**']

Prisma Schema:
- changed-files:
  - any-glob-to-any-files: ['server/prisma/**']

CI/CD:
- changed-files:
  - any-glob-to-any-files: ['.github/workflows/**', '.github/actions/**', '**/Dockerfile', 'docker-compose.prod.yml']

DX:
- changed-files:
  - any-glob-to-any-files: ['**/README.md']
