# Source: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - dependencies
  categories:
<<<<<<< HEAD
    - title: Web App
      labels:
        - Front
        - Layout
    - title: Server
      labels:
        - Back
=======
>>>>>>> c01c174 (Gtihub: Add Changelog & Publish action)
    - title: Exciting New Features 🎉
      labels:
        - Feature
        - Basic
    - title: Improvement, Optmizations & Enhancements 👍
      labels:
        - Enhancement/Optimization
    - title: Fixes & Patches 🩹
      labels:
        - Bug
        - Quick Fix
    - title: Security 🛡
      labels:
        - Security
        - Logs
    - title: Documentation 📖
      labels:
        - Documentation
    - title: CI/CD ⚙
      labels:
        - CD/CD
    - title: Codebase-related 📑
      labels:
        - Coding Style
        - Testing
        - Architecture
    - title: Other Changes 🔀
      labels:
        - "*"