# Source: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: Exciting New Features 🎉
      labels:
        - Feature
        - Basic
    - title: Improvements, Optmizations & Enhancements 👍
      labels:
        - Enhancement/Optimization
        - Layout
    - title: Fixes & Patches 🩹
      labels:
        - Bug
        - Fixes
    - title: Documentation 📖
      labels:
        - Documentation
    - title: Security 🛡
      labels:
        - Security
    - title: Deployment ⚙
      labels:
        - CI/CD
    - title: Other Changes 🔀
      labels:
        - "*"
