# This compose allows to setup the whole project in the production environment 
services:
  server:
    image: ghcr.io/arthi-chaud/meelo-server:edge
    expose:
      - 4000
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - config:/meelo
      - data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 5
  front:
    image: ghcr.io/arthi-chaud/meelo-front:edge
    expose:
      - 3000
    depends_on:
      server:
        condition: service_healthy
    environment:
      - PUBLIC_SERVER_URL=${PUBLIC_SERVER_URL}
      - SSR_SERVER_URL=http://server:4000
  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:alpine3.14
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    restart: on-failure
    image: nginx:1.24.0-alpine
    depends_on:
      server:
        condition: service_started
      front:
        condition: service_started
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - FRONT_URL=http://front:3000
      - SERVER_URL=http://server:4000
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/meelo.conf.template:ro
volumes:
  db:
  config:
  data:
