services:
  meelo:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
      - "4000:4000"
    depends_on:
      db:
       condition: service_healthy
    volumes:
      - ../data/config:/meelo
      - ../assets:/app/assets
      - ../front:/app/front
      - ../server:/app/server
      - ../data:/data
    env_file:
      - .env
  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:alpine3.16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
