services:
  meelo:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    ports:
      - "5000:5000"
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - "db"
    volumes:
      - ../meelo:/meelo
      - ../assets:/app/assets
      - ../front:/app/front
      - ../server:/app/server
      - ../data:/data
    env_file:
      - .env
  db:
    image: postgres:alpine3.16
    env_file:
      - .env
