// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get Status of Scanner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/clean": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Request a Clean",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/clean/{libraryId}": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Request a Clean for a single library",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Library Slug or ID",
                        "name": "libraryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Exactly one query parameter must be given",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Refresh Metadata of selected files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "refresh files from library",
                        "name": "library",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "refresh files from album",
                        "name": "album",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "refresh files from release",
                        "name": "release",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "refresh files from song",
                        "name": "song",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "refresh file from track",
                        "name": "track",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "force metadata refresh, even if files have not changed (default: false)",
                        "name": "force",
                        "in": "query"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/scan": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Request a Scan for all libraries",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/scan/{libraryId}": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Request a Scan for a single library",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Library Slug or ID",
                        "name": "libraryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerStatus"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tasks"
                ],
                "summary": "Get Current + Pending Tasks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.ScannerTaskStatus"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ScannerStatus": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "main.ScannerTaskStatus": {
            "type": "object",
            "properties": {
                "current_task": {
                    "description": "Name of the currently running task",
                    "type": "string"
                },
                "pending_tasks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "progress": {
                    "description": "Progress (0-100) of the running task. Can be null",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "description": "Prefix the value with ` + "`" + `Bearer ` + "`" + `",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Meelo's Scanner API",
	Description:      "The scanner is responsible for file parsing and registration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
