FROM node:22-alpine3.20 AS base
RUN apk update && apk add openssl

FROM base AS builder
WORKDIR /app
COPY ./*.json ./
COPY ./*.lock ./
COPY .yarn ./.yarn
COPY .yarnrc.yml ./
RUN corepack enable
RUN yarn
COPY ./prisma ./prisma
RUN yarn build

CMD yarn							\
	&& yarn build					\
	&& yarn run prisma migrate dev	\
	&& yarn start:dev
