FROM node:18-alpine3.18 AS base
RUN apk update && apk add openssl1.1-compat

FROM base AS builder
WORKDIR /app
COPY ./*.json ./
COPY ./*.lock ./
RUN yarn
COPY ./prisma ./prisma
RUN yarn build

CMD yarn							\
	&& yarn build					\
	&& yarn run prisma migrate dev	\
	&& yarn start:dev