FROM node:18-alpine3.18
WORKDIR /app
COPY ./*.json ./
COPY ./*.lock ./
COPY ./.yarnrc.yml ./
COPY ./.yarn /app/.yarn
RUN yarn install

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD yarn && yarn run start:dev