name: 'Cache (Front)'
description: 'Cache for Front'
runs:
  using: "composite"
  steps:
    - name: Add build dependencies to container
      shell: sh
      run: apk add --update --no-progress tar
    - name: Cache
      uses: actions/cache@v3
      with:
          path: |
            ./front/node_modules
            ./front/.next
          key: front-${{ hashFiles('front/yarn.lock') }}
          restore-keys: front-
