name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Create .env file"
        run: |
          echo 'DATABASE_URL="postgresql://test:test@postgres:5432/test?schema=public"' >> .env
      - name: Build Containers
        run: docker-compose build