name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - section: 'server'
            pwd: ./server
          - section: 'front'
            pwd: ./front
    name: Build ${{ matrix.section }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build (and deploy)
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.pwd }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: arthichaud/meelo-${{ matrix.section }}:latest
          cache-from: type=registry,ref=arthichaud/meelo-${{ matrix.section }}:latest
