name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Create .env file"
        run: |
          echo "BACK_PORT=8080" > .env
          echo 'DATABASE_URL="postgresql://test:test@postgres:5432/test?schema=public"' >> .env
      - name: Build Containers
        run: docker-compose -f docker-compose.dev.yml build
      - name: Start Meelo
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Check front-end response
        run: curl localhost:8080 -f > /dev/null
      - name: Check back-end response
        run: curl localhost:8080/api -f > /dev/null
      - name: Stop Meelo
        run: docker-compose -f docker-compose.dev.yml stop