name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: github.ref != 'refs/heads/master'
        name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
      - if: github.ref == 'refs/heads/master'
        name: Build and deploy
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: arthichaud/meelo:latest
          cache-from: type=registry,ref=arthichaud/meelo:latest
