name: Generate and Deploy Documentation
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn --cwd server install
      - name: Generate Documentation
        run: yarn  --cwd server compodoc -p tsconfig.json --hideGenerator --disableDependencies --disableCoverage
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/generated
          branch: docs