name: Documentation
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  Changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '.github/workflows/documentation.yml'
              - 'assets/**'
  Build:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.docs == 'true' }}
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: docs/mkdocs.yml
          REQUIREMENTS: docs/requirements.txt