name: "iOS Build"
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

defaults:
  run:
    working-directory: ./front/apps/mobile

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: macos-26
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Get Tag & Build Changelog
        shell: bash
        if: ${{ github.event_name == 'release' }}
        run: |
          echo "EXPO_PUBLIC_BUILD_COMMIT=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

          echo "WHATS_NEW=This version of the app is compatible with Meelo ${{ github.event.release.tag_name }}. Using the app with a mismatched version may cause unexpected behaviour. For more information, check out the changelog on GitHub." >> $GITHUB_ENV
      - name: Get Commit & Build Changelog
        shell: bash
        if: ${{ github.event_name != 'release' }}
        run: |
          export BUILD_COMMIT=$(git rev-parse --short ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }})
          echo "EXPO_PUBLIC_BUILD_COMMIT=$BUILD_COMMIT" >> $GITHUB_ENV

          echo "WHATS_NEW=${{ github.event_name == 'pull_request' &&  github.event.pull_request.title || github.event.head_commit.message }}. Warning: This version of the app was built from the main branch (commit $BUILD_COMMIT). Make sure to update your instance using the edge tag, and pull the latest images." >> $GITHUB_ENV
      - name: Import Certs
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - name: Download Store Provisioning Profile
        id: dl_store_prof
        uses: apple-actions/download-provisioning-profiles@v4
        with:
          bundle-id: "com.arthichaud.meelo"
          profile-type: "IOS_APP_STORE"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      - name: Get Profile Info
        run: |
          echo "PROFILE_UUID=$(echo '${{ steps.dl_store_prof.outputs.profiles }}' | jq -r '.[-1].udid')" >> $GITHUB_ENV
          echo "PROFILE_NAME=$(echo '${{ steps.dl_store_prof.outputs.profiles }}' | jq -r '.[-1].name')" >> $GITHUB_ENV
      - name: Restore Dependencies
        uses: ./.github/actions/cache-front
      - name: Install Dependencies
        run: yarn workspaces focus -A
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Prebuild
        run: |
          yarn run expo prebuild -p ios
          CI=1 yarn run ios --no-bundler
      # NOTE: Caching Pods does not improve compilation time
      - name: Set Version and Build number
        run: |
          cd ios
          xcrun agvtool new-marketing-version "$(echo ${{ github.event_name == 'release' && '$EXPO_PUBLIC_BUILD_COMMIT' || '0.1'  }} | tr -d v)"
          xcrun agvtool new-version "$(date '+%Y%m%d')${{ github.run_number }}"
      - name: Define Export Options
        run: |
          cd ios
          cat > ExportOptions.plist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.arthichaud.meelo</key>
                  <string>${{ env.PROFILE_NAME }}</string>
              </dict>
              <key>signingStyle</key>
              <string>manual</string>
              <key>uploadSymbols</key>
              <true/>
            </dict>
            </plist>
            EOF
      - name: Archive
        run: |
          cd ios
          xcodebuild \
            -workspace Meelo.xcworkspace \
            -scheme Meelo \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -sdk iphoneos \
            -archivePath build/Meelo.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE=${{ env.PROFILE_UUID }} \
            CODE_SIGN_IDENTITY="iPhone Distribution"

      - name: Export IPA
        run: |
          cd ios
          xcodebuild \
            -exportArchive \
            -archivePath build/Meelo.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/Meelo
      - name: Get IPA Path
        run: echo "IPA_PATH=${{ format('{0}/front/apps/mobile/ios/build/Meelo/Meelo.ipa', github.workspace) }}" >> $GITHUB_ENV
      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v4
        with:
          app-path: ${{ env.IPA_PATH }}
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
          release-notes: ${{ env.WHATS_NEW }}
          # NOTE: When false, release notes are not uploaded :/
          wait-for-processing: "true"
          backend: AppStoreAPI
      - name: Upload IPA
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: Meelo.ipa
          path: ${{ env.IPA_PATH }}
      - name: Add IPA to release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: |
            ${{ env.IPA_PATH }}
