name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarnnpm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true