name: Sonar Cloud Analysis

on:
  push:
    branches:
      - '*'

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: run_unit_tests
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 30
      - uses: actions/checkout@v2
      - name: Downlad Coverage artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: unit-tests.yml
          name: coverage-report
          path: coverage
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN }}