name: Unit tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    container: node:17
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: "Create .env file"
        run: |
          echo 'DATABASE_URL="postgresql://test:test@postgres:5432/test?schema=public"' > .env
      - name: Install test dependencies
        run: yarn install
      - name: Migrate DB Schema
        run: yarn test:db:migrate
      - name: Run unit tests
        run: yarn test