name: Unit tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test