name: Unit tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    container: node:17
    services:
      db:
        image: postgres:alpine3.16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: "Create .env file"
        run: |
          echo "POSTGRES_USER=test" >> .env
          echo "POSTGRES_PASSWORD=test" >> .env
          echo "POSTGRES_DB=test" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "BACK_PORT=8080" >> .env
          echo 'DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public"' > .env1
      - name: Install test dependencies
        run: yarn install
      - name: Migrate DB Schema
        run: yarn test:db:migrate
      - name: Run unit tests
        run: yarn test