name: Unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run_unit_tests_front:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    container: node:18-alpine3.18
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3
      - name: Install test dependencies
        run: yarn install
      - name: Run unit tests with coverage
        run: yarn test --coverage
      - name: Upload Unit Tests artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-front
          path: front/coverage
