name: Unit tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Create .env file"
        run: |
          echo "POSTGRES_USER=test" >> .env
          echo "POSTGRES_PASSWORD=test" >> .env
          echo "POSTGRES_DB=test" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "BACK_PORT=8080" >> .env
          echo 'DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public"' > .env1
      - name: Build container
        run: docker-compose -f docker-compose.dev.yml build
      - name: Run container
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Run unit tests
        run: yarn test