name: Unit tests

on: [push, pull_request, workflow_dispatch]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    container: node:17
    services:
      postgres:
        image: postgres:alpine3.16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: "Create .env file"
        run: |
          echo 'DATABASE_URL="postgresql://test:test@postgres:5432/test?schema=public"' > .env
          echo "${{ secrets.GENIUS_ACCESS_TOKEN }}" >> .env
      - name: Install test dependencies
        run: yarn install
      - name: Migrate DB Schema
        run: yarn test:db:migrate
      - name: Run unit tests with coverage
        run: yarn test --coverage
      - name: Upload Unit Tests artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage