name: Unit tests

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
        echo '
        POSTGRES_USER=Meelo
        POSTGRES_PASSWORD=M3EL0diI
        POSTGRES_DB=meelo
        POSTGRES_HOST=db
        BACK_PORT=8080
        DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?schema=public"
        ' > .env1
      - run: docker-compose -f docker-compose.dev.yml build